# Generated by Django 4.2 on 2023-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1200, null=True)),
                ('keyword', models.CharField(blank=True, max_length=1200, null=True)),
                ('alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=1200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1200, null=True)),
                ('keyword', models.CharField(blank=True, max_length=1200, null=True)),
                ('alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=1200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('sidename', models.CharField(blank=True, max_length=230, null=True)),
                ('sidecontent', models.TextField(blank=True, null=True)),
                ('sideimage1', models.ImageField(blank=True, null=True, upload_to='')),
                ('sideimage2', models.ImageField(blank=True, null=True, upload_to='')),
                ('bottomimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Xeber',
                'verbose_name_plural': 'Xeberler',
            },
        ),
        migrations.CreateModel(
            name='HomeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('href', models.CharField(blank=True, max_length=1200, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeHeaderVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1200, null=True)),
                ('keyword', models.CharField(blank=True, max_length=1200, null=True)),
                ('alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=800)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1200, null=True)),
                ('keyword', models.CharField(blank=True, max_length=1200, null=True)),
                ('alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=800)),
                ('content', models.TextField()),
                ('coverimage', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
