# Generated by Django 4.2 on 2023-09-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ordering',
        ),
    ]
