# Generated by Django 4.2 on 2023-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0002_remove_article_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
