# Generated by Django 4.2 on 2023-09-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0004_category_tag_article_category_article_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
