# Generated by Django 4.2 on 2023-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0005_remove_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='ordering',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
