# Generated by Django 4.2 on 2023-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0009_blog_content_without_ck_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keyword',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='keyword',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='keyword',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo'),
        ),
    ]
