# Generated by Django 4.2 on 2023-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0010_alter_article_description_alter_article_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=1200, unique=True),
        ),
    ]
