# Generated by Django 4.2 on 2023-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0011_alter_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bottomcontent',
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='bottomname',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
