# Generated by Django 4.2 on 2023-09-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0014_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
    ]
