# Generated by Django 4.2.5 on 2023-10-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyderapp', '0016_about_article_content_az_article_content_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='content_en',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='minititle_en',
            new_name='minititle_ru',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title_en',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content_en',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name_en',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='bottomcontent_en',
            new_name='bottomcontent_ru',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='bottomname_en',
            new_name='bottomname_ru',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content_en',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content_without_ck_en',
            new_name='content_without_ck_ru',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='name_en',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='sidecontent_en',
            new_name='sidecontent_ru',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='sidename_en',
            new_name='sidename_ru',
        ),
        migrations.RenameField(
            model_name='homeheader',
            old_name='content_en',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='homeheader',
            old_name='title_en',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='homeheadervideo',
            old_name='name_en',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='content_en',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name_en',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='content_en',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='name_en',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='content_en',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name_en',
            new_name='name_ru',
        ),
    ]
